### ISSUE TITLE
SQF Language Server Error

### ISSUE THREAD

**Issue by bux** [Armitxes/VSCode_SQF#29] opened 2019-02-13 09:37 UTC
VS Code about output
```
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

An error shows up in the output windows after opening an sqf file.

```fs.js:157
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at c:\Users\bux\.vscode\extensions\armitxes.sqf-1.0.6\server\events.js:39:20
    at fs.js:753:9
    at FSReqWrap.oncomplete (fs.js:169:20)
[Info  - 10:30:21] Connection to server got closed. Server will restart.
[Error - 10:30:22] Notification handler 'workspace/didChangeConfiguration' failed with message: c:\Users\bux\.vscode\extensions\armitxes.sqf-1.0.6\syntaxes\sqf.min.json: Unexpected end of JSON input
```

![image](https://user-images.githubusercontent.com/1235520/52701538-bc1c5600-2f7a-11e9-9812-b6789c8b7888.png)

After reloading the highlighting doesn't work anymore and I get the following new error message in the output window.

```
[Error - 10:33:51] Notification handler 'workspace/didChangeConfiguration' failed with message: c:\Users\bux\.vscode\extensions\armitxes.sqf-1.0.6\syntaxes\sqf.min.json: Unexpected end of JSON input
```

When inspecting the sqf.min.json it's just an empty  0kb file.

![image](https://user-images.githubusercontent.com/1235520/52701648-00a7f180-2f7b-11e9-8d6d-012d02b1fe84.png)

**Comment by Tanin69** [comment] 2019-03-05 07:49
Same problem for me. Have found any workaround, bux ?

**Comment by Armitxes** [comment] 2019-03-05 09:12
Sorry for the late answer. Had to deal with 2 other projects.

This issue occurs since Visual Studio Code introduced a feature which this extension already had.
Reloading itself once the config is changed. Had this solved for myself but I can't remember how :/ will try to reproduce and release a fix.

The issue also no longer occurs in milestone branch for fresh installs so the fix must be in there ^^
Give me a bit to test it out ;)

**Comment by bux** [comment] 2019-03-05 09:24
![image](https://user-images.githubusercontent.com/1235520/53794738-da99bf80-3f30-11e9-915b-ca01e7874d7d.png)

https://github.com/Armitxes/VSCode_SQF/blob/master/server/events.js#L38

**Comment by bux** [comment] 2019-03-05 09:25
^For reference ... how veteran and I fixed it on our side.

**Comment by Armitxes** [comment] 2019-03-05 21:00
Yea that's still back from the time where we had absolutely no documentation for VS Code.
It was pure learning by reverse engineering, trying things out ^^ and by looking into the extensions of Microsoft itself.

I remember that one of the big issues back then was that we had no possibility to properly change the provided highlighting based on custom settings.

Will fix it.

**Comment by Armitxes** [comment] 2019-03-08 19:48
Fixed in development.
https://github.com/Armitxes/VSCode_SQF/commit/5b5c991f28a81110479974b53ce0ae15f09559e8

Releasing it this weekend together with some new features.

**Comment by Armitxes** [comment] 2019-03-10 12:02
Fixed and released :) Thanks for reporting

**Closed as completed by Armitxes** 2019-03-10 12:02 UTC
Labels: bug, solved
